
// Sign Up
export const SIGN_UP = "AUTH-SIGN_UP/SIGN_UP";
export const SIGN_UP_SUCCESS = "AUTH-SIGN_UP/SIGN_UP_SUCCESS";

// Login
export const LOGIN = "AUTH-LOGIN/LOGIN";
export const LOGIN_SUCCESS = "AUTH-LOGIN/LOGIN_SUCCESS";

//Loader
export const SET_LOADING_STATUS = "LOADER/SET_LOADING_STATUS";
export const REMOVE_LOADING_STATUS = "LOADER/REMOVE_LOADING_STATUS";

// Fetch Home Data
export const FETCH_HOME_FEED = "HOME/FETCH_HOME_FEED";
export const FETCH_HOME_FEED_SUCCESS = "HOME/FETCH_HOME_FEED_SUCCESS";

// Fetch Subscription Data
export const FETCH_SUBSCRIPTIONS = "SUBSCRIPTIONS/FETCH_SUBSCRIPTIONS";
export const FETCH_SUBSCRIPTIONS_SUCCESS = "SUBSCRIPTIONS/FETCH_SUBSCRIPTIONS_SUCCESS";

// Fetch Profile Info
export const FETCH_PROFILE_INFO = "PROFILE/FETCH_PROFILE_INFO";
export const FETCH_PROFILE_INFO_SUCCESS = "PROFILE/FETCH_PROFILE_INFO_SUCCESS";

// Upload Post
export const UPLOAD_POST = "POST-UPLOAD/UPLOAD_POST";
export const UPLOAD_POST_SUCCESS = "POST-UPLOAD/UPLOAD_POST_SUCCESS";

// Logout
export const LOGOUT = "AUTH-LOGOUT/LOGOUT";
export const LOGOUT_SUCCESS = "AUTH-LOGOUT/LOGOUT_SUCCESS";

// Update Profile
export const UPDATE_PROFILE = "PROFILE/UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "PROFILE/UPDATE_PROFILE_SUCCESS";

// Fetch activites
export const FETCH_ACTIVITY = "ACTIVITY/FETCH_ACTIVITY";
export const FETCH_ACTIVITY_SUCCESS = "ACTIVITY/FETCH_ACTIVITY_SUCCESS";

// Set Active Tab
export const SET_ACTIVE_TAB = "TAB/SET_ACTIVE_TAB";
